### ISSUE TITLE
PCB program

### ISSUE THREAD

**Issue by Slowre** [makermoekoe/Hotplate-Soldering-Iron#1]
what program do you use to design the pcb

**Comment by dedekcz** [comment]
looks like Eagle

**Comment by skorokithakis** [comment]
Could we maybe get a Gerber export for fabrication? I use KiCAD and am not very familiar with Eagle, so it would take me a while to export.

**Comment by makermoekoe** [comment]
Sorry for the late response...
Yes, I am using Eagle all the time.
@skorokithakis I have added the gerber files in the PCB section. But I am currently working on a new reflow controller which can be used for the iron as well.
