### ISSUE TITLE
Resistor And Cap Values

### ISSUE THREAD

**Issue by Kperroch** [makermoekoe/Hotplate-Soldering-Iron#2]
Hello @makermoekoe , what are the resistor R1 and Capacitor C1 values ? 
They are not provided anywhere.

Many thanks

**Comment by makermoekoe** [comment]
The values can be found on my website (I have linked it above the readme): https://www.makermoekoe.net/post/maker-moekoe-s-kind-of-soldering-iron

Value of R1 is 10k, value of C1 is 0.1µ and potentiometer is 10k as well
